### ISSUE TITLE
how to avoid loading delay ? how it makes fasty ? 

### ISSUE THREAD

**Issue by aravinthk00** [sidvenu/MathJaxView#11]
how to avoid loading delay ? how it makes fasty ?
sometimes can't load and hang on that text at the point.

Thanks in advanced!

**Comment by sidvenu** [comment]
Hey @aravinthk00, it is generally advised not to use this or Katexview lib that i made because it is old without any maintenance.

But if you don't mind that, I suggest using sidvenu/KaTeXView, it is v fast compared to MathJaxView.

**Comment by aravinthk00** [comment]
thankyou for the information
