### ISSUE TITLE
Config should be set before initial settext, because now it is not used

### ISSUE THREAD

**Issue by Mikolasek93** [sidvenu/MathJaxView#4]
https://github.com/sidvenu/MathJaxView/blob/1c7092e7cc054ce754611c515873a389059aa4db/mathjaxview/src/main/java/io/github/sidvenu/mathjaxview/MathJaxView.java#L35

**Comment by sidvenu** [comment]
I guess this is one of the time I facepalmed hard as a developer. I tried changing the config hoping it would reflect in code, but to no avail. I thought the improvements fast-preview gives is just not noticeable. Thanks a ton!

**Comment by sidvenu** [comment]
a8e9939cc95faa5b5970792dd366912fa3c66a77 closes #4
