### ISSUE TITLE
setup with remote Maven repository

### ISSUE THREAD

**Issue by dragonhella** [sidvenu/MathJaxView#5]
hey 
first of all thanks for you great work.
i have tried to set up you project using maven repository and the files has been downloaded / synced successfully but i couldn't import the project into my java files or see the tags in my xml files any tips about how i could fix that 
thanks in advance

**Comment by sidvenu** [comment]
Could you elaborate on this issue? What error appears when you try to use the library?

**Comment by imarindam** [comment]
Same thing happened to me. I have added the dependency right. But Still cannot import it to my java or xml.

**Comment by sidvenu** [comment]
@imarindam please send me screenshots of what happens when you try to use it in Java/XML.

**Comment by sidvenu** [comment]
Fixed in the commit f65439adb3ad4943dc0032065c95e07ba98a6e79. `1.0.6` had ProGuard on that removed MathJaxView class from the .aar file, which I overlooked. Sincere apologies for that. Happy coding!
